stages:
  - lint
  - test_back
  - build_backend
  - build_frontend

eslint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npx eslint src/*.js

htmlhint:
  stage: lint
  image: node:latest
  script:
    - npm install htmlhint
    - npx htmlhint src/*.html
  except:
    - tags

stylelint:
  stage: lint
  image: node:latest
  script:
    - npm install csslint-cli
    - npx csslint-cli src/*.css

#test_backend:
#  stage: test_back
#  image: node
#  script:
#    - cd backend
#    - npm install
#    - npm test
#  only:
#    - main

#backend_build:
#  stage: build_backend
#  image: node:latest
#  script:
#    - cd node
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - ./dist

frontend_build:
  stage: build_frontend
  image: node:latest
  script:
    - mkdir -p public
    - mkdir -p public/images
    - cp index.html public/index.html
    - cp src/styles.css public/styles.css
    - cp -r src/images/* public/images/
    - cp src/*.js public/ 
  artifacts:
    paths:
      - public

